version: 3.0.7-{build}

environment:
  matrix:
  - GENERATOR: MinGW Makefiles
  - GENERATOR: Visual Studio 14 2015
  - GENERATOR: Visual Studio 14 2015 Win64

configuration: Debug

before_build:
  # Workaround for CMake not wanting sh.exe on PATH for MinGW
  - mv "C:/Program Files (x86)/Git/bin/sh.exe" "C:/Program Files (x86)/Git/bin/shxx.exe"
  - mv C:/Program Files/Git/bin/sh.exe C:/Program Files/Git/bin/shxx.exe
  - set PATH=C:\MinGW\bin;%PATH%
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=%CONFIGURATION% -G "%GENERATOR%" ..

build_script: cmake --build . --config %CONFIGURATION%
