version: 3.0.7-{build}

environment:
  matrix:
  - GENERATOR: MinGW Makefiles
  - GENERATOR: Visual Studio 14 2015
  - GENERATOR: Visual Studio 14 2015 Win64

configuration: Debug

before_build:
  # Workaround for CMake not wanting sh.exe on PATH for MinGW
  - set PATH=C:\MinGW\bin
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=%CONFIGURATION% -G "%GENERATOR%" ..

build_script: cmake --build . --config %CONFIGURATION%
